pipeline:
  loaders:    ["urdf_loader"]
  builders:   ["kin_builder", "dyn_builder", "reg_builder"]
  generators: ["robot_generator"]

urdf_loader:
  urdf_path: "dynaarm.urdf"
  base_link: "base"
  ee_link: "wrist_2"

  gravity:
    symb: [0,0,0]
    value: [0, 0, -9.81]

  # world to link_0
  Base_to_L0:
    symb: [0,0,0, 0,0,0]
    tr: [0, 0, 0]
    ypr: [0, 0, 0]

  # Link_n to EE
  Ln_to_EE:
    symb: [0,0,0, 0,0,0]
    tr: [0, 0, 0]
    ypr: [0, 0, 0]

robot_generator:
  gen_python:   false
  gen_casadi:   true
  gen_robot:    true
  copy_gen:     true
