pipeline:
  loaders:    ["urdf_loader"]
  builders:   ["kin_builder", "dyn_builder", "reg_builder"]
  generators: ["robot_generator"]


urdf_loader:
  urdf_path: "franka.urdf"
  base_link: "panda_link0"
  ee_link: "panda_link8"
  # Set to false to force numeric-only kinematics (par_KIN), otherwise symbolic.
  # Alternatively, set per-link masks using the link name.
  # Example:
  # symbolic_kinematics:
  #   panda_link0: [1, 1, 1, 1, 1, 1]
  #   panda_link1:
  #     xyz: [1, 1, 1]
  #     rpy: [0, 0, 0]
  symbolic_kinematics: true
  # Set to false to force numeric-only dynamics parameters (par_DYN), otherwise symbolic.
  # Can also be overridden per-link via a mask of 10 values (mass, CoM, inertia).
  # Example:
  # symbolic_dynamics:
  #   panda_link0: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  #   panda_link1:
  #     mass: 1
  #     com: [0, 1, 0]
  #     inertia: [1, 1, 1, 0, 0, 0]
  symbolic_dynamics: true

  # gravity
  gravity:
    symb: [0,0,0]
    value: [0, 0, -9.81]

  # world to link_0
  Base_to_L0:
    symb: [0,0,0, 0,0,0]
    tr: [0, 0, 0]
    ypr: [0, 0, 0]

  # Link_n to EE
  Ln_to_EE:
    symb: [0,0,0, 0,0,0]
    tr: [0, 0, 0]
    ypr: [0, 0, 0]

robot_generator:
  gen_python:   false
  gen_casadi:   true
  gen_robot:    true
  copy_gen:     true