#include "plugins/generators/ros_server_generator.h"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#include <boost/algorithm/string.hpp>


namespace fs = std::filesystem;

namespace thunder_ns {
namespace {

struct GeneratorConfig {
    int frequency = 1000;
    bool real_time = false;
    bool copy_gen = false;
    std::vector<std::string> services;
    std::vector<std::string> topics;
    std::map<std::string, std::string> inputs;
};

void write_file(const fs::path& path, const std::string& content) {
    std::ofstream output(path);
    if (!output) {
        throw std::runtime_error("Unable to write generated file: " + path.string());
    }
    output << content;
}

void copy_generated_file(const fs::path& source, const fs::path& destination) {
    if (!fs::exists(source)) {
        throw std::runtime_error("Missing " + source.string() +
            ". ros_server_generator requires robot_generator to run first with gen_robot: true.");
    }
    fs::create_directories(destination.parent_path());
    fs::copy_file(source, destination, fs::copy_options::overwrite_existing);
    // fs::remove(source);
}

bool is_valid_ros_package_name(const std::string& name) {
    return !name.empty() && std::islower(static_cast<unsigned char>(name.front())) &&
           std::all_of(name.begin(), name.end(), [](unsigned char character) {
               return std::islower(character) || std::isdigit(character) || character == '_';
           });
}

GeneratorConfig parse_config(const YAML::Node& config) {
    GeneratorConfig result;
    if (config["frequency"]) result.frequency = config["frequency"].as<int>();
    if (config["real_time"]) result.real_time = config["real_time"].as<bool>();
    if (config["copy_gen"]) result.copy_gen = config["copy_gen"].as<bool>();
    if (config["services"]) result.services = config["services"].as<std::vector<std::string>>();
    if (config["topics"]) result.topics = config["topics"].as<std::vector<std::string>>();
    if (config["inputs"]) result.inputs = config["inputs"].as<std::map<std::string, std::string>>();
    if (result.frequency <= 0) throw std::runtime_error("ros_server_generator.frequency must be positive.");
    return result;
}

std::vector<std::string> selected_names(
    const YAML::Node& raw_selection,
    const std::map<std::string, Function>& functions,
    const std::map<std::string, Parameter>& parameters,
    const char* field,
    bool default_all) {
    std::vector<std::string> result;
    if (!raw_selection && default_all) {
        for (const auto& function : functions) result.push_back(function.first);
        for (const auto& parameter : parameters) {
            if (parameter.second.symb_size() != 0) result.push_back(parameter.first);
        }
        return result;
    }
    if (!raw_selection) return result;

    std::set<std::string> seen;
    for (const auto& name : raw_selection.as<std::vector<std::string>>()) {
        if (!functions.count(name) && !parameters.count(name)) {
            throw std::runtime_error("ros_server_generator." + std::string(field) +
                                     " contains unknown robot quantity '" + name + "'.");
        }
        if (parameters.count(name) && parameters.at(name).symb_size() == 0) {
            throw std::runtime_error("Parameter '" + name +
                                     "' has no runtime (symbolic) entries and cannot be exposed.");
        }
        if (!seen.insert(name).second) {
            throw std::runtime_error("ros_server_generator." + std::string(field) +
                                     " contains duplicate quantity '" + name + "'.");
        }
        result.push_back(name);
    }
    return result;
}


std::string package_xml(const std::string& package_name) {
    return  "<?xml version=\"1.0\"?>\n"
            "<package format=\"3\">\n"
            "  <name>" + package_name + "</name>\n"
            "  <version>0.1.0</version>\n"
            "  <description>ROS 2 interfaces generated by Thunder Dynamics.</description>\n"
            "  <maintainer email=\"maintainer@example.com\">Thunder Dynamics</maintainer>\n"
            "  <license>Apache-2.0</license>\n"
            "  <buildtool_depend>ament_cmake</buildtool_depend>\n"
            "  <buildtool_depend>rosidl_default_generators</buildtool_depend>\n"
            "  <depend>rclcpp</depend>\n"
            "  <depend>std_msgs</depend>\n"
            "  <depend>realtime_tools</depend>\n"
            "  <depend>eigen</depend>\n"
            "  <depend>yaml-cpp</depend>\n"
            "  <member_of_group>rosidl_interface_packages</member_of_group>\n"
            "  <exec_depend>rosidl_default_runtime</exec_depend>\n"
            "  <export>\n"
            "    <build_type>ament_cmake</build_type>\n"
            "  </export>\n"
            "</package>\n";
}

std::string cmake_lists(const std::string& package_name, const std::string& robot_name) {
    return  "cmake_minimum_required(VERSION 3.16)\n"
            "project(" + package_name + ")\n\n"
            "find_package(ament_cmake REQUIRED)\n"
            "find_package(rclcpp REQUIRED)\n"
            "find_package(std_msgs REQUIRED)\n"
            "find_package(realtime_tools REQUIRED)\n"
            "find_package(Eigen3 REQUIRED)\n"
            "find_package(yaml-cpp REQUIRED)\n"
            "find_package(rosidl_default_generators REQUIRED)\n\n"
            "rosidl_generate_interfaces(${PROJECT_NAME}\n"
            "  \"srv/Compute.srv\"\n"
            "  \"srv/GetParameter.srv\"\n"
            "  \"srv/SetParameter.srv\"\n"
            ")\n\n"
            "add_executable(" + robot_name + "_server_node\n"
            "  src/" + robot_name + "_server_node.cpp\n"
            "  src/thunder_" + robot_name + ".cpp\n"
            "  src/" + robot_name + "_gen.cpp\n"
            ")\n"
            "target_compile_features(" + robot_name + "_server_node PUBLIC cxx_std_17)\n"
            "target_include_directories(" + robot_name + "_server_node PRIVATE include include/${PROJECT_NAME} src)\n"
            "target_link_libraries(" + robot_name + "_server_node Eigen3::Eigen yaml-cpp)\n"
            "ament_target_dependencies(" + robot_name + "_server_node rclcpp std_msgs realtime_tools)\n"
            "rosidl_get_typesupport_target(cpp_typesupport_target ${PROJECT_NAME} \"rosidl_typesupport_cpp\")\n"
            "target_link_libraries(" + robot_name + "_server_node \"${cpp_typesupport_target}\")\n\n"
            "install(TARGETS " + robot_name + "_server_node DESTINATION lib/${PROJECT_NAME})\n"
            "install(DIRECTORY include/ DESTINATION include)\n"
            "install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})\n"
            "ament_export_dependencies(rosidl_default_runtime)\n"
            "ament_package()\n";
}

std::string launch_file(const std::string& package_name, const std::string& robot_name) {
    return  "from launch import LaunchDescription\n"
            "from launch_ros.actions import Node\n\n"
            "def generate_launch_description():\n"
            "    return LaunchDescription([\n"
            "        Node(\n"
            "            package='" + package_name + "',\n"
            "            executable='" + robot_name + "_server_node',\n"
            "            name='" + package_name + "',\n"
            "            output='screen',\n"
            "        ),\n"
            "    ])\n";
}

std::string server_source(
    const std::string& package_name,
    const std::string& robot_name,
    int frequency,
    bool real_time,
    const std::vector<std::string>& services,
    const std::vector<std::string>& topics,
    const std::map<std::string, std::string>& inputs,
    const std::map<std::string, Function>& functions,
    const std::map<std::string, Parameter>& parameters) {
    std::ostringstream code;
    string robot_name_lowerCase = boost::algorithm::to_lower_copy(robot_name);

    code << "#include <algorithm>\n#include <chrono>\n#include <cstdint>\n#include <functional>\n#include <memory>\n#include <string>\n#include <vector>\n\n"
         << "#include <pthread.h>\n#include <sched.h>\n#include <rclcpp/rclcpp.hpp>\n#include <std_msgs/msg/float32_multi_array.hpp>\n#include <realtime_tools/realtime_buffer.hpp>\n"
         << "#include <" << package_name << "/srv/compute.hpp>\n#include <" << package_name << "/srv/get_parameter.hpp>\n#include <" << package_name << "/srv/set_parameter.hpp>\n"
         << "#include <" << package_name << "/thunder_" << robot_name << ".h>\n\n"
         << "namespace {\nusing FloatArray = std_msgs::msg::Float32MultiArray;\n"
         << "template<typename Matrix> std::vector<float> flatten_row_major(const Matrix& matrix) {\n"
         << "  std::vector<float> values; values.reserve(matrix.rows() * matrix.cols());\n"
         << "  for (Eigen::Index row = 0; row < matrix.rows(); ++row) for (Eigen::Index column = 0; column < matrix.cols(); ++column) values.push_back(static_cast<float>(matrix(row, column)));\n"
         << "  return values;\n}\n"
         << "}  // namespace\n\n"
         << "class " << robot_name << "Server : public rclcpp::Node {\npublic:\n"
         << "  " << robot_name << "Server() : Node(\"" << robot_name << "_server\") {\n";

    for (const auto& input : inputs) {
        code << "    " << input.first << "_subscription_ = create_subscription<FloatArray>(\"" << input.second
             << "\", rclcpp::QoS(1), [this](FloatArray::SharedPtr message) { " << input.first
             << "_buffer_.writeFromNonRT(message->data); });\n";
    }

    for (const auto& name : services) {
        if (functions.count(name)) {
            const Function& function = functions.at(name);
            int input_size = 0;
            for (const auto& argument : function.explicit_args) input_size += argument.size();
            code << "    " << name << "_service_ = create_service<" << package_name << "::srv::Compute>(\"" << name
                 << "\", [this](const std::shared_ptr<" << package_name << "::srv::Compute::Request> request, std::shared_ptr<"
                 << package_name << "::srv::Compute::Response> response) {\n"
                 << "      if (request->input.size() != " << input_size << ") { RCLCPP_WARN(get_logger(), \"" << name
                 << " expects " << input_size << " explicit input values\"); return; }\n";
            int offset = 0;
            for (const auto& argument : function.explicit_args) {
                code << "      Eigen::Matrix<double, " << argument.size() << ", 1> " << argument.name << ";\n"
                     << "      for (std::size_t index = 0; index < " << argument.size() << "; ++index) " << argument.name
                     << "(index) = request->input[" << offset << " + index];\n";
                offset += argument.size();
            }
            code << "      const auto result = robot_.get_" << name << "(";
            for (std::size_t index = 0; index < function.explicit_args.size(); ++index) {
                if (index) code << ", ";
                code << function.explicit_args[index].name;
            }
            code << "); response->output = flatten_row_major(result);\n    });\n";
        } else {
            const int size = parameters.at(name).symb_size();
            code << "    get_" << name << "_service_ = create_service<" << package_name << "::srv::GetParameter>(\"get_" << name
                 << "\", [this](const std::shared_ptr<" << package_name << "::srv::GetParameter::Request>, std::shared_ptr<"
                 << package_name << "::srv::GetParameter::Response> response) { const auto value = robot_.get_" << name
                 << "(); response->value.assign(value.data(), value.data() + " << size << "); });\n"
                 << "    set_" << name << "_service_ = create_service<" << package_name << "::srv::SetParameter>(\"set_" << name
                 << "\", [this](const std::shared_ptr<" << package_name << "::srv::SetParameter::Request> request, std::shared_ptr<"
                 << package_name << "::srv::SetParameter::Response> response) {\n"
                 << "      if (request->value.size() != " << size << ") { response->success = false; response->message = \"Expected " << size << " values\"; return; }\n"
                 << "      Eigen::Matrix<double, " << size << ", 1> value; for (std::size_t index = 0; index < " << size << "; ++index) value(index) = request->value[index];\n"
                 << "      robot_.set_" << name << "(value); response->success = true;\n    });\n";
        }
    }

    for (const auto& name : topics) {
        code << "    " << name << "_publisher_ = create_publisher<FloatArray>(\"" << name << "\", rclcpp::QoS(1));\n";
    }
    code << "    timer_ = create_wall_timer(std::chrono::microseconds(" << (1000000 / frequency)
         << "), std::bind(&" << robot_name << "Server::on_timer, this));\n  }\n\nprivate:\n"
         << "  void on_timer() {\n";
    for (const auto& input : inputs) {
        const int size = parameters.at(input.first).symb_size();
        code << "    if (const auto* latest = " << input.first << "_buffer_.readFromRT(); latest && latest->size() == " << size << ") {\n"
             << "      Eigen::Matrix<double, " << size << ", 1> value; for (std::size_t index = 0; index < " << size << "; ++index) value(index) = (*latest)[index]; robot_.set_"
             << input.first << "(value);\n    }\n";
    }
    for (const auto& name : topics) {
        code << "    { FloatArray message;";
        if (functions.count(name)) code << " const auto value = robot_.get_" << name << "(); message.data = flatten_row_major(value);";
        else code << " const auto value = robot_.get_" << name << "(); message.data.assign(value.data(), value.data() + " << parameters.at(name).symb_size() << ");";
        code << " " << name << "_publisher_->publish(message); }\n";
    }
    code << "  }\n\n  thunder_" << robot_name << " robot_;\n  rclcpp::TimerBase::SharedPtr timer_;\n";
    for (const auto& input : inputs) {
        code << "  realtime_tools::RealtimeBuffer<std::vector<float>> " << input.first << "_buffer_;\n"
             << "  rclcpp::Subscription<FloatArray>::SharedPtr " << input.first << "_subscription_;\n";
    }
    for (const auto& name : services) {
        if (functions.count(name)) code << "  rclcpp::Service<" << package_name << "::srv::Compute>::SharedPtr " << name << "_service_;\n";
        else code << "  rclcpp::Service<" << package_name << "::srv::GetParameter>::SharedPtr get_" << name << "_service_;\n"
                  << "  rclcpp::Service<" << package_name << "::srv::SetParameter>::SharedPtr set_" << name << "_service_;\n";
    }
    for (const auto& name : topics) code << "  rclcpp::Publisher<FloatArray>::SharedPtr " << name << "_publisher_;\n";
    code << "};\n\nint main(int argc, char** argv) {\n  rclcpp::init(argc, argv);\n";
    if (real_time) {
        code << "  sched_param priority{}; priority.sched_priority = 25;\n"
             << "  if (pthread_setschedparam(pthread_self(), SCHED_FIFO, &priority) != 0) {\n"
             << "    RCLCPP_WARN(rclcpp::get_logger(\"" << package_name + "\"), \"Unable to enable SCHED_FIFO priority 25; continuing normally\");\n  }\n";
    }
    code << "  rclcpp::spin(std::make_shared<" << robot_name << "Server>());\n  rclcpp::shutdown();\n  return 0;\n}\n";
    return code.str();
}

}  // namespace

void ROSServerGenerator::generate(const std::shared_ptr<Robot> robot) {
    const GeneratorConfig settings = parse_config(config_);
    const std::string robot_name = robot->robotName;
    const std::string package_name = boost::algorithm::to_lower_copy(robot_name) + "_server";
    std::cout << "Generating ROS 2 package '" << package_name << "' for robot '" << robot_name << "'...\n";
    if (!is_valid_ros_package_name(package_name)) {
        throw std::runtime_error("ROS 2 package names must be lowercase letters, digits, and underscores. Robot name '" +
                                 robot_name + "' cannot produce a standard package name.");
    }

    const std::vector<std::string> services = selected_names(config_["services"], robot->functions, robot->parameters, "services", true);
    const std::vector<std::string> topics = selected_names(config_["topics"], robot->functions, robot->parameters, "topics", false);
    for (const auto& input : settings.inputs) {
        if (!robot->parameters.count(input.first)) throw std::runtime_error("ros_server_generator.inputs contains unknown parameter '" + input.first + "'.");
        if (robot->parameters.at(input.first).symb_size() == 0) throw std::runtime_error("Input parameter '" + input.first + "' has no runtime entries.");
        if (input.second.empty()) throw std::runtime_error("Input topic for parameter '" + input.first + "' is empty.");
    }

    const fs::path output_root = fs::current_path() / (robot_name + "_generatedFiles");
    const fs::path package_root = output_root / package_name;
    const fs::path include_dir = package_root / "include" / package_name;
    const fs::path source_dir = package_root / "src";
    fs::create_directories(include_dir);
    fs::create_directories(source_dir);
    fs::create_directories(package_root / "srv");
    fs::create_directories(package_root / "launch");
    fs::create_directories(package_root / "config");

    // The ROS generator consumes the C++ robot created by robot_generator.
    // Moving these sources keeps one authoritative copy in the ROS package.
    if (fs::exists(output_root / "pyproject.toml")) {
        throw std::runtime_error("ros_server_generator cannot move a Python-enabled robot_generator output. Set robot_generator.gen_python to false.");
    }
    copy_generated_file(output_root / ("thunder_" + robot_name + ".h"), include_dir / ("thunder_" + robot_name + ".h"));
    copy_generated_file(output_root / (robot_name + "_gen.h"), include_dir / (robot_name + "_gen.h"));
    copy_generated_file(output_root / ("thunder_" + robot_name + ".cpp"), source_dir / ("thunder_" + robot_name + ".cpp"));
    copy_generated_file(output_root / (robot_name + "_gen.cpp"), source_dir / (robot_name + "_gen.cpp"));
    copy_generated_file(output_root / (robot_name + "_conf.yaml"), package_root / "config" / (robot_name + "_conf.yaml"));
    copy_generated_file(output_root / (robot_name + "_par.yaml"), package_root / "config" / (robot_name + "_par.yaml"));

    write_file(package_root / "package.xml", package_xml(package_name));
    write_file(package_root / "CMakeLists.txt", cmake_lists(package_name, robot_name));
    write_file(package_root / "srv" / "Compute.srv", "float32[] input\n---\nfloat32[] output\n");
    write_file(package_root / "srv" / "GetParameter.srv", "---\nfloat32[] value\n");
    write_file(package_root / "srv" / "SetParameter.srv", "float32[] value\n---\nbool success\nstring message\n");
    write_file(package_root / "launch" / (package_name + ".launch.py"), launch_file(package_name, robot_name));

    // - write the ROS server node - //
    write_file(source_dir / (robot_name + "_server_node.cpp"), server_source(package_name, robot_name, settings.frequency,
               settings.real_time, services, topics, settings.inputs, robot->functions, robot->parameters));

    if ((settings.copy_gen) && fs::exists("/home/thunder_dev/thunder_dynamics")) {
        fs::path destination = "/home/thunder_dev/thunder_dynamics";
        destination = destination / "src" / "thunder_ros_test" / "src" / package_name;
        fs::create_directories(destination.parent_path());
        fs::copy(package_root, destination, fs::copy_options::recursive | fs::copy_options::overwrite_existing);
    }
    debug_log("Generated ROS 2 package " + package_name, VERB_INFO);
}

}  // namespace thunder_ns
