#ifndef GEN_UTILS_H
#define GEN_UTILS_H

#include <vector>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iostream>
#include <string>

#include "robot.h"
#include "utils.h"

using std::endl;
using std::string;
using std::vector;

namespace thunder_ns {

int create_thunder_robot(const string robot_name, Robot& robot, const string file_h, const string file_cpp, const bool gen_python);


// --- CREATE THUNDER ROBOT --- //
int create_thunder_robot(const string robot_name, Robot& robot, const string file_h, const string file_cpp, const bool gen_python){
	
	// --- get everything from robot --- //
	string robotName = robot.robotName;
	int n_joints = robot.get<int>("numJoints");
	int Dl_order = robot.get<int>("Dl_order");
	bool ELASTIC = robot.get<bool>("ELASTIC");

	int numElasticJoints = 0;
	std::vector<short> isElasticJoint = {0};
	int K_order = 0;
	int D_order = 0;
	int Dm_order = 0;
	if (ELASTIC) {
		numElasticJoints = robot.get<int>("numElasticJoints");
		isElasticJoint = robot.get<vector<short>>("isElasticJoint");
		K_order = robot.get<int>("K_order");
		D_order = robot.get<int>("D_order");
		Dm_order = robot.get<int>("Dm_order");
	}
	
	// int STD_PAR_LINK = robot.STD_PAR_LINK;
	const std::map<string, Property>& properties = robot.properties;
	const std::map<string, par_obj>& parameters = robot.parameters;
	const std::map<string, fun_obj>& functions = robot.functions;
	// std::vector<fun_obj> functions = robot.get_functions();

	// -------------------------------- //
	// --- Create thunder_<robot>.h --- //
	// -------------------------------- //

	string file_content_h = "";

	// - generate headers - //
	file_content_h.append("#ifndef THUNDER_" + robot_name + "_H\n");
	file_content_h.append("#define THUNDER_" + robot_name + "_H\n\n");
	file_content_h.append(
		"#include <iostream>\n"
		"#include <string>\n"
		"#include <cmath>\n"
		"#include <eigen3/Eigen/Dense>\n"
		"#include <yaml-cpp/yaml.h>\n"
		"#include <fstream>\n\n");
	
	// - insert namespace of common type classes - //
	file_content_h.append(
		"using std::string;\n"
		"using std::vector;\n"
		"using std::map;\n"
		"using Eigen::MatrixXd;\n"
		"using Eigen::VectorXd;\n"
		"using Eigen::Matrix;\n"
		"using Eigen::Vector;\n\n");
	
	// --- class and private members --- //
	string thunder_robot_name = "thunder_" + robot_name;
	file_content_h.append(
	"\n"
	"// ------------------- //\n"
	"// --- ROBOT CLASS --- //\n"
	"// ------------------- //\n\n");
	file_content_h.append(
		"// Contains all the properties, parameters, and functions generated by CadADi\n"
		"class " + thunder_robot_name + "{\n"
			"\tprivate:\n");
	
	// --- insert parameters --- //
	string parameters_str = 
	"\n"
	"\t\t// ------------------ //\n"
	"\t\t// --- Parameters --- //\n"
	"\t\t// ------------------ //\n"
	"\n";
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			parameters_str.append(
				"\t\t// " + par.second.description + "\n"
				"\t\tVector<double," + std::to_string(par.second.size()) + "> " + par.second.name + " = " + par.second.get_value_str() + ";\n");
			}
		}
	file_content_h.append(parameters_str + "\n");

	// --- public members --- //
	file_content_h.append(
			"\n"
			"\tpublic:\n\n"
				"\t\t// ------------------ //\n"
				"\t\t// --- Properties --- //\n"
				"\t\t// ------------------ //\n\n"
				"\t\t// Robot name\n"
				"\t\tconst string robotName = \"" + robot_name + "\";\n");

	// --- insert properties --- //
	string properties_str = "\n";
	for (auto prop : properties){
		properties_str.append(
			"\t\t// " + prop.second.description + "\n"
			"\t\tconst " + prop.second.type_str + " " + prop.second.name + " = " + prop.second.get_value_str() + ";\n");
	}
	file_content_h.append(properties_str + "\n");

	// --- insert functions --- //
	string functions_str = 
		"\n"
		"\t\t// ----------------- //\n"
		"\t\t// --- Functions --- //\n"
		"\t\t// ----------------- //\n"
		"\n"
		"\t\t// Default constructor\n"
		"\t\tthunder_" + robot_name + "();\n\n";

	// - parameters gets - //
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			string fun_name = "get_" + par.second.name;
			int out_size = par.second.symb_size();
			functions_str.append("\t\t// get the parameter: " + par.second.name + "\n");
			functions_str.append("\t\tVector<double," + std::to_string(out_size) + "> " + fun_name + "();\n");
		}
	}

	// - parameters sets - //
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			string fun_name = "set_" + par.second.name;
			int in_size = par.second.symb_size();
			functions_str.append("\t\t// set the parameter: " + par.second.name + "\n");
			functions_str.append("\t\tvoid " + fun_name + "(Vector<double,"+std::to_string(in_size)+"> value);\n");
		}
	}

	// - save parameters to file - //
	functions_str.append(
		"\n"
		"\t\t/**\n\t\t * @brief Save parameters to file\n"
		"\t\t * \n"
		"\t\t * @param  par_file:  parameter file\n"
		"\t\t * \n"
		"\t\t * @param  par_list={}:  list of parameters to save ({} means all parameters)\n"
		"\t\t * \n"
		"\t\t * @return  1: succeed,  0: failed\n"
		"\t\t */ \n"
		"\t\tint save_par(string par_file, vector<string> par_list = {});\n");

	// - load parameters from file - //
	functions_str.append(
		"\n"
		"\t\t/**\n\t\t * @brief Load parameters from file\n"
		"\t\t * \n"
		"\t\t * @param  par_file:  parameter file\n"
		"\t\t * \n"
		"\t\t * @param  par_list={}:  list of parameters to load ({} means all parameters)\n"
		"\t\t * \n"
		"\t\t * @return  1: succeed,  0: failed\n"
		"\t\t */ \n"
		"\t\tint load_par(string par_file, vector<string> par_list = {});\n");


	// - robot functions - //
	functions_str.append("\n");
	for (auto fun : functions){
		// - description - //
		functions_str.append(
			"\t\t/**\n\t\t * @brief " + fun.second.description + "\n"
			"\t\t * \n"
			"\t\t * - depends on: " + fun.second.get_args_str() + "\n"
			"\t\t */ \n");
		// - declaration - //
		functions_str.append("\t\t"+fun.second.get_ret_type_str()+" get_" + fun.second.name + "();\n\n");
	}
	file_content_h.append(functions_str + "};\n"
	"#endif\n");

	// --- Save thunder_<robot>.h --- //
	std::ofstream out_h(file_h);
	out_h << file_content_h;
	out_h.close();


	// ---------------------------------- //
	// --- Create thunder_<robot>.cpp --- //
	// ---------------------------------- //

	string file_content_cpp = 
		"#include \"" + thunder_robot_name + ".h\"\n"
		"#include \"" + robot_name + "_gen.h\"\n\n";

	// --- insert python bindings --- //
	if(gen_python){
		string bindings_str = 
			"#include <pybind11/pybind11.h>\n"
			"#include <pybind11/eigen.h>\n"
			"\n"
			"// --------------------------- //\n"
			"// ----- Python bindings ----- //\n"
			"// --------------------------- //\n"
			"namespace py = pybind11;\n"
			"PYBIND11_MODULE("+thunder_robot_name+"_py, m) {\n"
			"\tpy::class_<"+thunder_robot_name+">(m, \""+thunder_robot_name+"\")\n"
			"\t\t.def(py::init<>())\n";
		// --- pybind properties --- //
		for (auto prop : properties){
			bindings_str.append("\n\t\t.def_readonly(\""+prop.second.name+"\", &"+thunder_robot_name+"::"+prop.second.name+", \""+ prop.second.description +"\")");
		}
		// --- pybind parameters gets/sets --- //
		bindings_str.append("\n");
		// - gets - //
		for (auto par : parameters){
			bindings_str.append("\n\t\t.def(\"get_"+par.second.name+"\", &"+thunder_robot_name+"::get_"+par.second.name+")");
		}
		// - sets - //
		for (auto par : parameters){
			bindings_str.append("\n\t\t.def(\"set_"+par.second.name+"\", &"+thunder_robot_name+"::set_"+par.second.name+")");
		}
		// --- pybind functions --- //
		bindings_str.append("\n");
		for (auto fun : functions){
			string fun_name = "get_" + fun.second.name;
			bindings_str.append("\n\t\t.def(\"" + fun_name + "\", &" + thunder_robot_name + "::" + fun_name + ", \""+ fun.second.description +"\")");
		}
		file_content_cpp.append(bindings_str + ";\n}\n");
	}

	// --- insert functions --- //
	// - constructor - //
	functions_str = "\n"
		"thunder_" + robot_name + "::thunder_" + robot_name + "(){}\n\n";

	// - parameters gets - //
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			string fun_name = "get_" + par.second.name;
			int out_size = par.second.symb_size();
			functions_str.append("// get the parameter: " + par.second.name + "\n");
			functions_str.append(
				"Vector<double," + std::to_string(out_size) + "> " + thunder_robot_name + "::" + fun_name + "() {return " + par.second.name + ";}\n");
		}
	}

	// - parameters sets - //
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			string fun_name = "set_" + par.second.name;
			int in_size = par.second.symb_size();
			functions_str.append("// set the parameter: " + par.second.name + "\n");
			functions_str.append(
				"void " + thunder_robot_name + "::" + fun_name + "(Vector<double,"+std::to_string(in_size)+"> value) {" + par.second.name + " = value;}\n");
		}
	}


	// - Save parameters to file - //
	string save_par_fun_str = "\n"
		"// Save parameters to file\n"
		"int " + thunder_robot_name + "::save_par(string par_file, vector<string> par_list){\n"
			"\tYAML::Node yamlFile;\n\n";
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			string par_name = par.second.name;
			save_par_fun_str.append(
			"\tif ((par_list.size()==0)||(std::count(par_list.begin(), par_list.end(), \""+par_name+"\"))){\n"
				"\t\tvector<double> " + par_name + "_vect("+par_name+".data(), "+par_name+".data() + "+std::to_string(par.second.symb_size())+");\n"
				"\t\tyamlFile[\""+par_name+"\"] = "+par_name+"_vect;\n"
			"\t}\n"
			);
		}
	}
	save_par_fun_str.append(
		"\n"
		"\ttry {\n"
			"\t\tYAML::Emitter emitter;\n"
			"\t\temitter.SetIndent(2);\n"
			"\t\temitter.SetSeqFormat(YAML::Flow);\n"
			"\t\temitter << yamlFile << YAML::Newline;\n"
			"\t\tstd::ofstream fout(par_file);\n"
			"\t\tfout << emitter.c_str();\n"
			"\t\tfout.close();\n"
		"\t} catch (const YAML::Exception& e) {\n"
			"\t\tstd::cerr << \"Error while generating YAML: \" << e.what() << std::endl;\n"
			"\t\treturn 0;\n"
		"\t}\n"
		"\treturn 1;\n"
		"}\n\n"
	);
	functions_str.append(save_par_fun_str);
	

	// - Load parameters from file - //
	string load_par_fun_str = "\n"
		"// Load parameters from file\n"
		"int " + thunder_robot_name + "::load_par(string par_file, vector<string> par_list){\n"
			"\tYAML::Node yamlFile;\n"
			"\ttry {\n"
				"\t\tyamlFile = YAML::LoadFile(par_file);\n\n"
			"\t} catch (const YAML::Exception& e) {\n"
				"\t\tstd::cerr << \"Error while loading parameters: \" << e.what() << std::endl;\n"
				"\t\treturn 0;\n"
			"\t}\n\n";
	for (auto par : parameters){
		if (par.second.symb_size() != 0){
			string par_name = par.second.name;
			load_par_fun_str.append(
			"\tif ((par_list.size()==0)||(std::count(par_list.begin(), par_list.end(), \""+par_name+"\"))){\n"
				"\t\tif (yamlFile[\""+par_name+"\"]){\n"
					"\t\t\tvector<double> vec(yamlFile[\""+par_name+"\"].as<vector<double>>());\n"
					"\t\t\t"+par_name+" = Eigen::Map<Vector<double,"+std::to_string(par.second.symb_size())+">>(vec.data(), vec.size());\n"
				"\t\t} else {\n"
					"\t\t\tstd::cerr << \"Error while loading parameters: "+par_name+" not found!\" << std::endl;\n"
					"\t\t\treturn 0;\n"
				"\t\t}\n"
			"\t}\n"
			);
		}
	}
	load_par_fun_str.append(
		"\n"
		"\treturn 1;\n"
		"}\n\n"
	);
	functions_str.append(load_par_fun_str);
	

	// - robot functions - //
	functions_str.append("\n");
	for (auto fun : functions){
		string fun_name = "get_" + fun.second.name;
		string fun_name_gen = robotName + "_" + fun.second.name;
		std::vector<string> fun_args = fun.second.args;
		std::vector<long> out_size = fun.second.get_out_size();
		// // function arguments
		// string args_string = "(" + fun_args[0];
		// for (int j=1; j<fun_args.size(); j++){
		// 	args_string.append(", " + fun_args[j]);
		// }
		// other parts
		string ret_type = fun.second.get_ret_type_str();
		functions_str.append("// " + fun.second.description + "\n");
		functions_str.append(ret_type + " thunder_" + robot_name + "::" + fun_name + "(){\n");
		// functions_str.append("\tEigen::MatrixXd out;\n");
		// functions_str.append("\tout.resize("+to_string(out_size[0])+","+to_string(out_size[1])+");\n");
		string size_str = std::to_string(out_size[0]*out_size[1]);
		functions_str.append("\tthread_local double buffer["+size_str+"];\n"); // alignas("+size_str+") 
		functions_str.append("\tthread_local long long p3[" + fun_name_gen + "_fun_SZ_IW];\n");
		functions_str.append("\tthread_local double p4[" + fun_name_gen + "_fun_SZ_W];\n");
		// inputs
		if (fun_args.size() == 0){
			functions_str.append("\tconst double** input_ = nullptr;\n");
		} else {
			functions_str.append("\tconst double* input_[] = {" + fun_args[0]+".data()");
			for (int j=1; j<fun_args.size(); j++){
				functions_str.append(", " + fun_args[j]+".data()");
			}
			functions_str.append("};\n");
		}
		// output
		functions_str.append("\tdouble* output_[] = {buffer};\n");
		functions_str.append("\tint check = " + fun_name_gen + "_fun(input_, output_, p3, p4, 0);\n");
		functions_str.append("\treturn Eigen::Map<"+ret_type+">(buffer);\n");
		functions_str.append("}\n\n");

	}
	file_content_cpp.append(functions_str);

	// --- overwrite file_cpp --- //
	std::ofstream out_cpp(file_cpp);
	out_cpp << file_content_cpp;
	out_cpp.close();

	return 1;
}

}

#endif